### ISSUE TITLE
RuboCop: Enable Gemspec/DateAssignment cop

### ISSUE THREAD

**Issue by tnir** [n-ronn/nronn#24]
Follows up #21

```yaml
# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: Include.
# Include: **/*.gemspec
Gemspec/DateAssignment:
  Exclude:
    - 'nronn.gemspec'
```
