### ISSUE TITLE
RuboCop: Enable Lint/DuplicateBranch cop

### ISSUE THREAD

**Issue by tnir** [n-ronn/nronn#25]
Follows up #21

```yaml
# Offense count: 7
# Configuration parameters: IgnoreLiteralBranches, IgnoreConstantBranches.
Lint/DuplicateBranch:
  Exclude:
    - 'lib/ronn/roff.rb'
```
